# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-0edc06b6-7e47-4cc8-84bd-fa472f1a698a";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-0edc06b6-7e47-4cc8-84bd-fa472f1a698a".device = "/dev/disk/by-uuid/0edc06b6-7e47-4cc8-84bd-fa472f1a698a";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/4B7B-ACD8";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
